using Deftility.Data;
using Deftility.Services.Contracts;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Deftility.Services.Seeding
{
    public class SkillsSeeder : ISeeder
    {
        public async Task SeedAsync(ApplicationDbContext context, IServiceProvider serviceProvider)
        {
            if (!context.Skills.Any())
            {
                var skillsService = serviceProvider.GetRequiredService<ISkillsService>();

                // better for this to be imported from a json (someday but not today)
                var skillsList = new List<string>()
                {
                    ".NET Core",
                    "3D Modeling",
                    "Adobe Photoshop",
                    "Adobe InDesign",
                    "Adobe Illustrator",
                    "Adobe After Effects",
                    "Adobe Audition",
                    "Adobe Premiere Pro",
                    "Application Security",
                    "Artificial Intelligence",
                    "Android",
                    "Audio Editing",
                    "Algebra",
                    "AWS",
                    "API",
                    "Audacity",
                    "AutoCAD",
                    "Automation",
                    "Angular",
                    "Animation",
                    "Augmented Reality",
                    "Advertising",
                    "Arduino",
                    "Bug Fixing",
                    "Blender",
                    "Branding",
                    "Brand Marketing",
                    "Brand Consulting",
                    "Bot Development",
                    "Blockchain",
                    "Bitcoin",
                    "Biochemistry",
                    "Business Analysis",
                    "Brochure",
                    "Business Card",
                    "Banners",
                    "Catalog",
                    "Clip Studio Paint",
                    "Cloud Computing",
                    "Content Writing",
                    "Cryptocurrency",
                    "C",
                    "CSS",
                    "C++",
                    "C#",
                    "Chemical Engineering",
                    "Cosmetics",
                    "Concept Art",
                    "Character",
                    "Cybersecurity",
                    "Docker",
                    "Digital Art",
                    "Drawing",
                    "Data Mining",
                    "Data Scraping",
                    "Database",
                    "Django",
                    "Ethical Hacking",
                    "English",
                    "Editing",
                    "Electronics",
                    "Electrical Engineering",
                    "eCommerce",
                    "EDM",
                    "Electro",
                    "Food & Supplements",
                    "Fashion",
                    "Financial Analysis",
                    "Flyer Design",
                    "Facebook Advertising",
                    "Google Cloud",
                    "Google Ads",
                    "Game Programming",
                    "Game Design",
                    "Geometry",
                    "German",
                    "Git",
                    "HTML",
                    "Information Security",
                    "Influencer Marketing",
                    "Instagram Marketing",
                    "Internet Marketing",
                    "Integration",
                    "Intro/Outro",
                    "iOS",
                    "Italian",
                    "Java",
                    "jQuery",
                    "JavaScript",
                    "Kubernetes",
                    "Keras",
                    "Logo Design",
                    "Linux",
                    "Magento",
                    "MATLAB",
                    "Microsoft Word",
                    "Microsoft Excel",
                    "Mixing",
                    "Mobile Game",
                    "Music Production",
                    "MS SQL",
                    "Machine Learning",
                    "Marketing",
                    "Marketing Strategy",
                    "NoSQL",
                    "Node.js",
                    "Neural Networks",
                    "Oracle",
                    "PHP",
                    "Photo Editing",
                    "Penetration Testing",
                    "Proofreading",
                    "Product Formulation",
                    "Python",
                    "PyTorch",
                    "PostgreSQL",
                    "Quality Control",
                    "QA Testing",
                    "Raspberry Pi",
                    "React",
                    "React Native",
                    "Redux",
                    "Real Estate",
                    "Responsive Web Design",
                    "Scripting",
                    "SQL",
                    "SEO",
                    "Salesforce",
                    "Spanish",
                    "Singing",
                    "Social Media Advertising",
                    "Social Media Management",
                    "TypeScript",
                    "TensorFlow",
                    "Tracking & Analytics",
                    "Tutoring",
                    "Trailer",
                    "Unreal Engine",
                    "Unity",
                    "UI/UX",
                    "VR",
                    "Video Editing",
                    "VueJS",
                    "Voice Acting",
                    "Voice Over",
                    "Website Creation",
                    "Website Security",
                    "Web Design",
                    "Web Scraping",
                    "WebGL",
                    "Wordpress",
                    "Wix",
                    "Writing",
                    "Xamarin",
                    "YouTube"
                };

                await skillsService.AddRangeAsync(skillsList);
            }
        }
    }
}
